version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: cat-pg-db
    environment: 
      POSTGRES_USER: admin2 
      POSTGRES_PASSWORD: admin123 
      POSTGRES_DB: bookshow_cat_db
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: